# Site settings
title: The Dackel Company
description: A Software Company
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://thedackel.company" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Conrad
user_description: Dackel Developer at The Dackel Co.
user_title: Dackel Developer
email: conrad@thedackel.company
twitter_username: thedackelcompany
github_username:  thedackelcompany
gplus_username:  thedackelcompany
disqus_username: thedackelcompany

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
